apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: mq9bn610c-java-springboot
  janus-idp.io/tekton: mq9bn610c-java-springboot
  backstage.io/kubernetes-id: mq9bn610c-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mq9bn610c-java-springboot
resources:
- deployment.yaml
- route.yaml
- service.yaml
