apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: mq9bn610c-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/mq9bn610c-java-springboot-gitops